#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     slide,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    rightIR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    leftIR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    ring,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool safe = false;
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "movement.c"
#include "doLineFollow.c"
#include "Rigid.c"
#include "Cyborggoodstuff.c"

void initializeRobot();
task main()
{
  servo[ring] = 0;
  initializeRobot();
  waitForStart(); // Wait for the beginning of autonomous phase.
  //doRidgid();

  doCyborgVision();
  //doLineFollow();
  //doReleaseRing();
  while (true)
  {}
}
void initializeRobot()
{
  StartTask(updateLightSensors); //No robot movement only reads light sensors
  servo[ring] = 0;
  servo[claw] = 0;
  return;
}
